<a href="https://colab.research.google.com/github/nishant-sheoran/Datascience/blob/main/DS_L1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Numpy

In [19]:
import numpy as np
np.__version__

'1.26.4'

In [18]:
range_array = np.arange(1,10,2)
print(range_array)

linspace_array = np.linspace(1,10,5)
print(linspace_array)

random_array = np.random.rand(3,3)
print(random_array)

[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]
[[0.48087075 0.09419013 0.63210426]
 [0.93809333 0.62865679 0.60755154]
 [0.16772576 0.27485349 0.05760167]]


In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64


array joining: np.concat

In [5]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


Searhing: np.where

In [7]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


Sorting: np.sort

In [8]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


iterating through the array

In [9]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


Copying an Array

In [10]:
#Deep copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [11]:
#Shallow Copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Array Shape manipulation

In [12]:
#reshape()
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
#flatten
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.flatten()
print(newarr)

[1 2 3 4 5 6]


In [14]:
#identity array
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
#eye function
arr = np.eye(3, 3, k = -1)
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


##Excercise 1 | Numpy

In [20]:
# Ex1
import numpy as np
np.__version__

'1.26.4'

In [21]:
# Ex2  1D array
one_d_array = np.array([1, 2, 3, 4, 5])
print(one_d_array)

[1 2 3 4 5]


In [23]:
# Ex3 bool array
bool_arr = np.array([True, False, True, False, True])
print(bool_arr)

# Boolean Array from a numerical array using a condition
num_arr = np.array([1, 2, 3, 4, 5])
bool_arr_from_num = num_arr > 2
print(bool_arr_from_num)

[ True False  True False  True]
[False False  True  True  True]


In [24]:
# Exercise 4: Extract items that satisfy a condition
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition = arr % 2 == 0  # Even numbers
even_numbers = arr[condition]
print("Even numbers:", even_numbers)

Even numbers: [ 2  4  6  8 10]
Array with even numbers replaced by 0: [1 0 3 0 5 0 7 0 9 0]
Original array: [ 1  2  3  4  5  6  7  8  9 10]
New array with even numbers replaced by 0: [1 0 3 0 5 0 7 0 9 0]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]
Fibonacci sequence: [ 0  1  1  2  3  5  8 13 21 34]


In [25]:
# Exercise 5: Replace items that satisfy a condition
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 == 0] = 0  # Replace even numbers with 0
print("Array with even numbers replaced by 0:", arr)

Array with even numbers replaced by 0: [1 0 3 0 5 0 7 0 9 0]


In [26]:
# Exercise 6: Replace items that satisfy a condition without affecting the original array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
new_arr = np.where(arr % 2 == 0, 0, arr)  # Replace even numbers with 0 in a new array
print("Original array:", arr)
print("New array with even numbers replaced by 0:", new_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
New array with even numbers replaced by 0: [1 0 3 0 5 0 7 0 9 0]


In [27]:
# Exercise 7: Reshape an array
arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
print("Reshaped array:\n", reshaped_arr)

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# Exercise 8: Stack two arrays vertically
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
vertical_stack = np.vstack((arr1, arr2))
print("Vertical stack:\n", vertical_stack)

Vertical stack:
 [[1 2 3]
 [4 5 6]]


In [29]:
# Exercise 9: Stack two arrays horizontally
horizontal_stack = np.hstack((arr1, arr2))
print("Horizontal stack:", horizontal_stack)

Horizontal stack: [1 2 3 4 5 6]


In [31]:
# Exercise 10: Generate custom sequences without hardcoding
# Why this works as an answer to this question is because the values of the fibonoacci series are not hardcoded and changes in the values of n changes the output !
def fibonacci(n):
    fib_sequence = np.zeros(n, dtype=int)
    fib_sequence[0] = 0
    fib_sequence[1] = 1
    for i in range(2, n):
        fib_sequence[i] = fib_sequence[i-1] + fib_sequence[i-2]
    return fib_sequence
fib_seq = fibonacci(10)
print("Fibonacci sequence:", fib_seq)

Fibonacci sequence: [ 0  1  1  2  3  5  8 13 21 34]


##Pandas Prac

In [32]:
import pandas as pd
pd.__version__

'2.2.2'

In [37]:
series = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
print(series)

a    1
b    2
c    3
d    4
dtype: int64
